package store

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/myntra/cortex/pkg/executions"
	"github.com/myntra/cortex/pkg/js"
	"github.com/myntra/cortex/pkg/rules"
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *MessageType) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 uint8
		zb0001, err = dc.ReadUint8()
		if err != nil {
			return
		}
		(*z) = MessageType(zb0001)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z MessageType) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteUint8(uint8(z))
	if err != nil {
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z MessageType) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendUint8(o, uint8(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *MessageType) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 uint8
		zb0001, bts, err = msgp.ReadUint8Bytes(bts)
		if err != nil {
			return
		}
		(*z) = MessageType(zb0001)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z MessageType) Msgsize() (s int) {
	s = msgp.Uint8Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Messages) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			return
		}
		switch msgp.UnsafeString(field) {
		case "Rules":
			var zb0002 uint32
			zb0002, err = dc.ReadMapHeader()
			if err != nil {
				return
			}
			if z.Rules == nil && zb0002 > 0 {
				z.Rules = make(map[string]*rules.Rule, zb0002)
			} else if len(z.Rules) > 0 {
				for key := range z.Rules {
					delete(z.Rules, key)
				}
			}
			for zb0002 > 0 {
				zb0002--
				var za0001 string
				var za0002 *rules.Rule
				za0001, err = dc.ReadString()
				if err != nil {
					return
				}
				if dc.IsNil() {
					err = dc.ReadNil()
					if err != nil {
						return
					}
					za0002 = nil
				} else {
					if za0002 == nil {
						za0002 = new(rules.Rule)
					}
					err = za0002.DecodeMsg(dc)
					if err != nil {
						return
					}
				}
				z.Rules[za0001] = za0002
			}
		case "Records":
			var zb0003 uint32
			zb0003, err = dc.ReadMapHeader()
			if err != nil {
				return
			}
			if z.Records == nil && zb0003 > 0 {
				z.Records = make(map[string]*executions.Record, zb0003)
			} else if len(z.Records) > 0 {
				for key := range z.Records {
					delete(z.Records, key)
				}
			}
			for zb0003 > 0 {
				zb0003--
				var za0003 string
				var za0004 *executions.Record
				za0003, err = dc.ReadString()
				if err != nil {
					return
				}
				if dc.IsNil() {
					err = dc.ReadNil()
					if err != nil {
						return
					}
					za0004 = nil
				} else {
					if za0004 == nil {
						za0004 = new(executions.Record)
					}
					err = za0004.DecodeMsg(dc)
					if err != nil {
						return
					}
				}
				z.Records[za0003] = za0004
			}
		case "Scripts":
			var zb0004 uint32
			zb0004, err = dc.ReadMapHeader()
			if err != nil {
				return
			}
			if z.Scripts == nil && zb0004 > 0 {
				z.Scripts = make(map[string]*js.Script, zb0004)
			} else if len(z.Scripts) > 0 {
				for key := range z.Scripts {
					delete(z.Scripts, key)
				}
			}
			for zb0004 > 0 {
				zb0004--
				var za0005 string
				var za0006 *js.Script
				za0005, err = dc.ReadString()
				if err != nil {
					return
				}
				if dc.IsNil() {
					err = dc.ReadNil()
					if err != nil {
						return
					}
					za0006 = nil
				} else {
					if za0006 == nil {
						za0006 = new(js.Script)
					}
					err = za0006.DecodeMsg(dc)
					if err != nil {
						return
					}
				}
				z.Scripts[za0005] = za0006
			}
		default:
			err = dc.Skip()
			if err != nil {
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Messages) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "Rules"
	err = en.Append(0x83, 0xa5, 0x52, 0x75, 0x6c, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.Rules)))
	if err != nil {
		return
	}
	for za0001, za0002 := range z.Rules {
		err = en.WriteString(za0001)
		if err != nil {
			return
		}
		if za0002 == nil {
			err = en.WriteNil()
			if err != nil {
				return
			}
		} else {
			err = za0002.EncodeMsg(en)
			if err != nil {
				return
			}
		}
	}
	// write "Records"
	err = en.Append(0xa7, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.Records)))
	if err != nil {
		return
	}
	for za0003, za0004 := range z.Records {
		err = en.WriteString(za0003)
		if err != nil {
			return
		}
		if za0004 == nil {
			err = en.WriteNil()
			if err != nil {
				return
			}
		} else {
			err = za0004.EncodeMsg(en)
			if err != nil {
				return
			}
		}
	}
	// write "Scripts"
	err = en.Append(0xa7, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x73)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.Scripts)))
	if err != nil {
		return
	}
	for za0005, za0006 := range z.Scripts {
		err = en.WriteString(za0005)
		if err != nil {
			return
		}
		if za0006 == nil {
			err = en.WriteNil()
			if err != nil {
				return
			}
		} else {
			err = za0006.EncodeMsg(en)
			if err != nil {
				return
			}
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Messages) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "Rules"
	o = append(o, 0x83, 0xa5, 0x52, 0x75, 0x6c, 0x65, 0x73)
	o = msgp.AppendMapHeader(o, uint32(len(z.Rules)))
	for za0001, za0002 := range z.Rules {
		o = msgp.AppendString(o, za0001)
		if za0002 == nil {
			o = msgp.AppendNil(o)
		} else {
			o, err = za0002.MarshalMsg(o)
			if err != nil {
				return
			}
		}
	}
	// string "Records"
	o = append(o, 0xa7, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73)
	o = msgp.AppendMapHeader(o, uint32(len(z.Records)))
	for za0003, za0004 := range z.Records {
		o = msgp.AppendString(o, za0003)
		if za0004 == nil {
			o = msgp.AppendNil(o)
		} else {
			o, err = za0004.MarshalMsg(o)
			if err != nil {
				return
			}
		}
	}
	// string "Scripts"
	o = append(o, 0xa7, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x73)
	o = msgp.AppendMapHeader(o, uint32(len(z.Scripts)))
	for za0005, za0006 := range z.Scripts {
		o = msgp.AppendString(o, za0005)
		if za0006 == nil {
			o = msgp.AppendNil(o)
		} else {
			o, err = za0006.MarshalMsg(o)
			if err != nil {
				return
			}
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Messages) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			return
		}
		switch msgp.UnsafeString(field) {
		case "Rules":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				return
			}
			if z.Rules == nil && zb0002 > 0 {
				z.Rules = make(map[string]*rules.Rule, zb0002)
			} else if len(z.Rules) > 0 {
				for key := range z.Rules {
					delete(z.Rules, key)
				}
			}
			for zb0002 > 0 {
				var za0001 string
				var za0002 *rules.Rule
				zb0002--
				za0001, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					return
				}
				if msgp.IsNil(bts) {
					bts, err = msgp.ReadNilBytes(bts)
					if err != nil {
						return
					}
					za0002 = nil
				} else {
					if za0002 == nil {
						za0002 = new(rules.Rule)
					}
					bts, err = za0002.UnmarshalMsg(bts)
					if err != nil {
						return
					}
				}
				z.Rules[za0001] = za0002
			}
		case "Records":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				return
			}
			if z.Records == nil && zb0003 > 0 {
				z.Records = make(map[string]*executions.Record, zb0003)
			} else if len(z.Records) > 0 {
				for key := range z.Records {
					delete(z.Records, key)
				}
			}
			for zb0003 > 0 {
				var za0003 string
				var za0004 *executions.Record
				zb0003--
				za0003, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					return
				}
				if msgp.IsNil(bts) {
					bts, err = msgp.ReadNilBytes(bts)
					if err != nil {
						return
					}
					za0004 = nil
				} else {
					if za0004 == nil {
						za0004 = new(executions.Record)
					}
					bts, err = za0004.UnmarshalMsg(bts)
					if err != nil {
						return
					}
				}
				z.Records[za0003] = za0004
			}
		case "Scripts":
			var zb0004 uint32
			zb0004, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				return
			}
			if z.Scripts == nil && zb0004 > 0 {
				z.Scripts = make(map[string]*js.Script, zb0004)
			} else if len(z.Scripts) > 0 {
				for key := range z.Scripts {
					delete(z.Scripts, key)
				}
			}
			for zb0004 > 0 {
				var za0005 string
				var za0006 *js.Script
				zb0004--
				za0005, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					return
				}
				if msgp.IsNil(bts) {
					bts, err = msgp.ReadNilBytes(bts)
					if err != nil {
						return
					}
					za0006 = nil
				} else {
					if za0006 == nil {
						za0006 = new(js.Script)
					}
					bts, err = za0006.UnmarshalMsg(bts)
					if err != nil {
						return
					}
				}
				z.Scripts[za0005] = za0006
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Messages) Msgsize() (s int) {
	s = 1 + 6 + msgp.MapHeaderSize
	if z.Rules != nil {
		for za0001, za0002 := range z.Rules {
			_ = za0002
			s += msgp.StringPrefixSize + len(za0001)
			if za0002 == nil {
				s += msgp.NilSize
			} else {
				s += za0002.Msgsize()
			}
		}
	}
	s += 8 + msgp.MapHeaderSize
	if z.Records != nil {
		for za0003, za0004 := range z.Records {
			_ = za0004
			s += msgp.StringPrefixSize + len(za0003)
			if za0004 == nil {
				s += msgp.NilSize
			} else {
				s += za0004.Msgsize()
			}
		}
	}
	s += 8 + msgp.MapHeaderSize
	if z.Scripts != nil {
		for za0005, za0006 := range z.Scripts {
			_ = za0006
			s += msgp.StringPrefixSize + len(za0005)
			if za0006 == nil {
				s += msgp.NilSize
			} else {
				s += za0006.Msgsize()
			}
		}
	}
	return
}
